#version 460
/**
*   Hello-World Compute Shader
*   Utilises the debug_printf extension to say Hello from 
*   the current Compute Shader Invocation. 
*   ------------------
*   Ewan Burnett (EwanBurnettSK@Outlook.com)
*   2024/04/25
*/
#extension GL_EXT_debug_printf : require

void main()
{
    debugPrintfEXT("Hello from Thread (%d, %d, %d)\n", gl_GlobalInvocationID.x, gl_GlobalInvocationID.y, gl_GlobalInvocationID.z);
}